name: walplash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.1
  flutter_local_notifications: ^15.1.0+1
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path_provider: ^2.0.15
  pinterest_nav_bar: ^0.0.1+5
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/animal.jpg
    - assets/images/architecture.jpg
    - assets/images/film.jpg
    - assets/images/nature.jpg
    - assets/images/travel.jpg
    - assets/images/searchphotos.png

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster.ttf
    - family: Madurai
      fonts:
        - asset: assets/fonts/Madurai.ttf
    - family: Beau
      fonts:
        - asset: assets/fonts/beau.ttf
