name: walplash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  draggable_bottom_sheet: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster.ttf
    - family: Madurai
      fonts:
        - asset: assets/fonts/Madurai.ttf

